### ISSUE TITLE
Consider generating a Sprite for rollover thumbnails (.vtt)

### ISSUE THREAD

**Issue by solanex** [majamee/alpine-dash-hls#26]
Hi, 

We really like alpine-dash-hls and are starting to implement this encoder pipeline in our projects instead of coding our own ffmpeg scripts.

I have noticed you have started to include thumbnails for webvtt files for fluid-player and maybe others. I would like to request to use sprites instead of seperate thumbnails though, as this reduces webserver load and speeds up everything (only 1 file instead of lots)

We currently use the mt tool by mutschler to generate these sprites
https://github.com/mutschler/mt

Example of usage to get a sprite and vtt file generated with thumbs every 5 seconds:
`./mt-1.0.8-linux_amd64 -i 5 -w 120 -p 0 -d --header=false --webvtt=true video.mp4`

**Comment by majamee** [comment]
Hi,
Thank you very much for your feedback. I am happy you like my work so far.
Also thank you for your instructions how to improve on my webvtt generation.
I will certainly check it out, but I don't know when exactly I will find the time to do that. 
Hoping in the next few days, but as I am quite busy these days and that is just a spare time project, it will be probably somewhere in the next 2 weeks. If you want to apply a patch though, I am happy to check it out and merge it sooner.

**Comment by bardiir** [comment]
I'm not 100% sure if a hardcoded 5 second per frame are the best way to handle this. It feels more like a minimum, I would actually like to try to make this dynamically grow with the video so the amount of frames in the thumbnails doesn't exceed an upper limit of for example 400 preview thumbnails, on a 800px wide player that would be one preview each two pixels which feels like a good amount for a default. Otherwise the sprite could actually end up beeing extremely big by itself which could cause rendering issues on mobile devices considering the sometimes quite limited amounts of ram available there.

**Comment by solanex** [comment]
@bardiir yes, this is possible by replacing the **-i 5** parameter with the **numcaps** parameter and setting it to how many thumbnails one wants. mt will then automatically figure out the time between each thumbnail and write this to the vtt file.

**Comment by bardiir** [comment]
@solanex yeah I was just typing actually 😄 - looking at it mutschler/mt does actually support a "numcap" parameter instead of an interval too. So maybe we could just switch over to a numcap of 400 instead of i 5 at a breakpoint of 30 minutes of video or so.

**Comment by majamee** [comment]
@solanex I was just investigating your solution attempt further and in general I like it, but it seams to be total overkill in terms of file sizes:
The overall pipeline project here is less than 30 MB so far, the piece of software you recommend to use is alone more than double that size: 89,8 MB (89.792.734 Bytes)

Any ideas how to make the thumbnail preview generation not the biggest part of the project instead?

**Comment by majamee** [comment]
@solanex @bardiir I managed to add the sprite generation via the tool `mt` and it can be tested at:
`docker pull majamee/alpine-dash-hls:webvtt-mt` and a hosted demo at http://alpine-dash-hls.gq/demos/fluid-player

I managed to reduce the overload to about 21 mb, but it still seems enormous as this is about a 90% file increasement. Looking forward to your feedback.

**Comment by solanex** [comment]
@majamee Hmm I didn't realize the mt tool was so big.
Here is another project that should do the same thing, but its more of a ruby library so not sure how to call it from commandline and haven't tested it;

https://github.com/scaryguy/jwthumbs

another way would be to make the sprite using ffmpeg and imagemagick as described at this stackoverflow comment, however i'm not sure how to build the vtt file from that.

https://stackoverflow.com/a/20713276/1311515

**Comment by majamee** [comment]
@solanex Imagemagick and all its dependencies will increase also the file size about 17 mb already. Therefore I am thinking about writing an own solution based on the work I already have done in the branch `webvtt`. The solution is based on the idea here how ffmpeg could be used to create the sprite image, then the webvtt generation becomes the next challenge. For more information and code contributions, please have a look here: https://stackoverflow.com/questions/24604689/how-to-join-two-images-into-one-with-ffmpeg

**Comment by majamee** [comment]
@solanex @bardiir I modified my webvtt.sh script in order to generate one sprite image, adding as minimal overhead as possible - still a little less than 30 mb :smiley: 
You can check it out here:
`docker pull majamee/alpine-dash-hls:webvtt`

Plus I added the preview support also for videojs player. Up2date demos can be checked out at:
* http://alpine-dash-hls.gq/demos/fluid-player
* http://alpine-dash-hls.gq/demos/videojs

**Comment by bardiir** [comment]
@majamee if I ever get around having enough time to even move anything at all I'll look into optimizing the webvtt generation. Actually generating the index file souldn't be that much of a problem and we can also include caesium then. Alternatively lets discuss in the next days :)

**Comment by majamee** [comment]
Merged into master branch.

**Comment by majamee** [comment]
@solanex Btw. you can also easily use the webvtt-mt branch, if you shouldn't be satisfied with my own implementation. It uses the recommendation of yours to generate the sprites (https://github.com/mutschler/mt), but increases the container size a little as you can see here:
https://hub.docker.com/repository/docker/majamee/alpine-dash-hls/tags?page=1
